# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 110ad6d4aaac08aa8244b0107ae918ac063f3b2922dc196be68a04077d64097626b718d1d32eae34c7931b1f2efea0ed06ad7f2fe9e839711543de0d53de84bd

test:
  secret_key_base: 83d29ece35eaab32958c70a3a345f7a7d8d4c32d793363bab4b4a71bfbdb50f95c45bb1358420bd32bf71cf65ef54eba4ead5d13c96a8f8cbe0cfb62355fa899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
