---
name: ActiveRecord MySQL Enum
on: [push]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: activerecord_mysql_enum_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3, 3.4]
        gemfile:
        - Gemfile
        - gemfiles/activerecord_6_1.gemfile
        - gemfiles/activerecord_7_0.gemfile
        - gemfiles/activerecord_7_1.gemfile
        - gemfiles/activerecord_7_2.gemfile
        - gemfiles/activerecord_8_0.gemfile
        exclude:
        - ruby: 3.1
          gemfile: gemfiles/activerecord_8_0.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_MYSQL_HOST: 127.0.0.1
      DATABASE_MYSQL_USERNAME: user
      DATABASE_MYSQL_PASSWORD: password
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.29
        bundler-cache: true
    - run: RAILS_ENV=test bundle exec rake db:create db:migrate
    - run: bundle exec rspec

  build_success:
    if: always()
    needs:
      - tests
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
